# Generated by Django 3.0.7 on 2020-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invetory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_or_no', models.BooleanField(verbose_name='Куплино или нет')),
                ('activ_or_no', models.BooleanField(verbose_name='Применино или нет')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
                'db_table': 'invetory',
            },
        ),
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120, verbose_name='Название предмета')),
                ('item_pice', models.IntegerField(verbose_name='Цена предмета')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
                'db_table': 'magazin',
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele_predmet', models.CharField(db_index=True, max_length=120, verbose_name='Название предмета')),
                ('kol_hours', models.IntegerField(verbose_name='Количество часов')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'predmet',
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_prepod', models.CharField(db_index=True, max_length=120, verbose_name='Имя')),
                ('second_name_prepod', models.CharField(db_index=True, max_length=120, verbose_name='Фамилия')),
                ('login_prepod', models.CharField(db_index=True, max_length=120, verbose_name='Логин')),
                ('password_prepod', models.CharField(db_index=True, max_length=120, verbose_name='Пароль')),
                ('photo_prepod', models.ImageField(blank=True, upload_to='images/student', verbose_name='Аватар')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'prepod',
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='first_name_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='login',
            new_name='login_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='password_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='second_name',
            new_name='second_name_student',
        ),
        migrations.RemoveField(
            model_name='profes',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='age_student',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='student',
            name='coin',
            field=models.IntegerField(null=True, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_student',
            field=models.ImageField(blank=True, upload_to='images/student', verbose_name='Аватар'),
        ),
    ]
