# Generated by Django 3.0.7 on 2020-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0006_magazin_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='item_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Название предмета'),
        ),
    ]
