# Generated by Django 3.0.7 on 2020-09-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0008_auto_20200912_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
