# Generated by Django 3.0.7 on 2020-09-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0009_auto_20200912_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekcia',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL'),
        ),
    ]
