# Generated by Django 3.0.7 on 2020-09-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0010_lekcia_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invetory',
        ),
    ]
