# Generated by Django 3.0.7 on 2020-09-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0012_auto_20200913_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_student',
        ),
        migrations.AddField(
            model_name='student',
            name='photo_student',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='deti.Magazin', verbose_name='Аватар'),
        ),
    ]
