# Generated by Django 3.0.7 on 2020-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deti', '0014_auto_20200913_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dopkyrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dopkyrs_title', models.CharField(db_index=True, max_length=120, verbose_name='Название курса')),
                ('photo_kyrs', models.ImageField(blank=True, null=True, upload_to='images/kyrs', verbose_name='Фото курса')),
                ('kyrs_pice', models.IntegerField(verbose_name='Цена курса')),
            ],
            options={
                'verbose_name': 'Дополнительные курсы',
                'verbose_name_plural': 'Дополнительные курсы',
                'db_table': 'dopkyrs',
            },
        ),
    ]
